### ISSUE TITLE
Long strings don’t translate 

### ISSUE THREAD

**Issue by haqueo** [mayeenulislam/nagri-bangla#1]
This string doesn’t translate, likely because it’s too long
![CC6839C6-6E36-4698-A0BD-9B8A16A6D879](https://user-images.githubusercontent.com/20957075/111539378-b9961700-8765-11eb-9ef5-cb8aa8a85274.png)

আমি যদি ইংরেজির জন্য একটি ট্যাব যুক্ত করি তবে কি হবে?

**Comment by mayeenulislam** [comment]
I'm afraid, cannot recreate the issue. Tried in Google Chrome debugger and in MI phone using MI Browser and Chrome (Mobile).

![chrome-dev-tools](https://user-images.githubusercontent.com/4551598/111562923-37d3d700-87c1-11eb-8539-79760121628f.png)<br>
Figure: As in Chrome Dev Tools

![Android Chrome](https://user-images.githubusercontent.com/4551598/111562965-4d490100-87c1-11eb-995e-259fd511c371.jpg)<br>
Figure: As in Android Chrome

## Possible Reason
Javascript (which is the core of this application) is not allowed in the browser where you tried...

**Can we have more information about the browser and device where you tested?** You can browse the following link in the browser to test whether JS enabled or not: https://www.whatismybrowser.com/detect/is-javascript-enabled

**Comment by haqueo** [comment]
I’ve confirmed with that link that JavaScript is enabled on my browser. I’m using Safari 14 on iOS 14.4. Let me know if you can reproduce the issue with that

**Comment by haqueo** [comment]
And this is on an iPhone 12 Pro Max

**Comment by haqueo** [comment]
Seems to be working now.
