### ISSUE TITLE
সিলেটি ’ꠠ’ এবং বাংলা 'ড় এর পারস্পরিক রূপান্তর সমস্যা

### ISSUE THREAD

**Issue by Misbah460** [mayeenulislam/nagri-bangla#5]
@

## যে পরিবেশে ত্রুটিটি পেয়েছি
* ব্রাউযার: <আপনার ব্রাউযারের নাম লিখুন>
* জাভাস্ক্রিপ্ট সক্রিয়?: <হ্যাঁ/না> [এই লিংকে গেলে জানা যাবে](https://www.whatismybrowser.com/detect/is-javascript-enabled)
* কিভাবে আমরাও একই সমস্যা দেখতে পাবো?: <বিস্তারিত ধাপে ধাপে লিখুন>

**Comment by mayeenulislam** [comment]
Duplicate of #6
