### ISSUE TITLE
ড় অক্ষর রূপান্তর জনিত সমস্যা

### ISSUE THREAD

**Issue by Misbah460** [mayeenulislam/nagri-bangla#6]
আসসালামু আলাইকুম,
 আপনাদের এই মহান কাজের জন্য প্রথমেই কৃতজ্ঞতা জ্ঞাপন করছি। 
আমি যে ত্রুটিটি তা এখানে সংযুক্ত ছবি দুইটাতে বর্ণিত আছে।
ধন্যবাদ

* ব্রাউযার: <Google Chrome>
* জাভাস্ক্রিপ্ট সক্রিয়?: <হ্যাঁ> 
*  
![IMG_20210418_004523](https://user-images.githubusercontent.com/82726603/115123860-d92c9380-9fe0-11eb-892b-050ef5ac6ae9.jpg)
![IMG_20210418_004202](https://user-images.githubusercontent.com/82726603/115123863-db8eed80-9fe0-11eb-8d84-9de5df635005.jpg)

**Comment by mayeenulislam** [comment]
আপনার গোছানো তথ্যের জন্য আপনাকেও ধন্যবাদ।
তবে সফ্টওয়্যার ডিবাগিং-এর সময় টেকনিক্যাল তথ্য বেশি দরকারি হয়.... আমার মনে হচ্ছে, আপনার ডিভাইসের ব্রাউযারে ফন্ট এম্বেড সাপোর্ট ঠিকমতো কাজ করছে না। কারণ আপনার উপস্থাপিত ইস্যুটি আমরা ডেস্কটপে recreate করতে পারিনি। এছাড়া মোবাইলে Chromium ব্রাউযারেও রিক্রিয়েট করা যায়নি।<br>
![nagri-bangla](https://user-images.githubusercontent.com/4551598/115137755-c69a7480-a049-11eb-8022-ca29a3cb3695.png)

### সম্ভাব্য কারণসমূহ

1. আপনার ব্রাউযারে @font-face ফন্ট এম্বেড কাজ করে না
2. আপনার ডিভাইসে সিলেটি নাগরি অন্য কোনো ফন্ট ইন্সটল করা আছে, যার সাথে সুরমা ফন্ট হয়তো কনফ্লিক্ট করছে
